name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for poiting out the issue. We will try our best to review, test and resolve the issue."
        pr-message: "You are making a great impact! After we review and test the PR, your changes will be live! We thank you."
